version: '3'

services:
  web:
    build: ./DDGN
#    command: django-admin startproject DDGN #This will create the Django project
#    command: python manage.py collectstatic #This will run the server so we can test it is working
#    command: python manage.py runserver 0.0.0.0:8000 #This will run the server so we can test it is working
    command: gunicorn -c gunicorn.conf codingindfw.wsgi #From this point we use gunicorn to serve the project
    volumes:
      - ./DDGN:/DDGN
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    depends_on:
      - web
    command: nginx -g 'daemon off;'
    ports:
      - "80:80"
    volumes:
      - ./DDGN/static:/var/www/static
      - ./DDGN/media:/var/www/media
